name: Build for iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run build ios
        run: |
          npm i
          cd ios && pod install && cd ..
          npm run build:ios
